### ISSUE TITLE
Can't join lobbies without Compatibility Checker

### ISSUE THREAD

**Issue by AllieAran** [VisualError/CompatibilityChecker#1]
Cannot join lobbies that aren't using Compatibility Checker/Vanilla lobbies

Error:
Failed to join Modded Crew!
Missing mods:
Can't display: Host does not
have CompatibilityChecker!

**Comment by VisualError** [comment]
This is not a mod issue but a game one, you can still join vanilla lobbies and lobbies that don't use Compatibility Checker
but due to how the base game handles lobby joins, there are some lobbies that you just can not join for whatever weird reasons. I just replaced unhandled errors with the "Failed to join Modded Crew!" display.

For the display saying "Failed to join Modded Crew!" even in vanilla servers here is the answer:
I simply just haven't figured out a way to discern between modded lobbies and non-modded lobbies yet.
